default_language_version:
  python: python3

default_stages: [pre-commit, pre-push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: trailing-whitespace
      - id: pretty-format-json
      - id: check-json
      - id: check-xml
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: LICENSE
      - id: check-case-conflict
      - id: check-docstring-first
      - id: debug-statements
      - id: detect-private-key
      - id: name-tests-test
