# A workflow that runs on macos-latest and test with Python 3.13
name: macOS

# The "on" controls when the action will run.
# The workflow is triggered on push and pull request events for the main branch.
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains one job for macOS
  build:
    name: Build on macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test
        with:
          cache-path: ~/Library/Caches/pip
          cache-key-prefix: macos
