name: release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tomli

      - name: Get version from pyproject.toml
        id: get_version
        run: |
          echo "VERSION=$(python -c "
          import tomli
          with open('pyproject.toml', 'rb') as f:
              print(tomli.load(f)['project']['version'])
          ")" >> $GITHUB_OUTPUT

      - name: Load release template
        id: release
        run: |
          echo "BODY<<EOF" >> $GITHUB_OUTPUT
          cat .github/RELEASE.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.get_version.outputs.VERSION }}
          release_name: Release v${{ steps.get_version.outputs.VERSION }}
          body: ${{ steps.release.outputs.BODY }}
